notes_application_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("notes_library.urls", namespace="notes_library")),

]
app_name = "notes_application_service"

notes_library/urls.py
from django.urls import path, include

from notes_library.views import (
    index,
    get_notes_view,
    get_categories_view,
    create_note_view,
    delete_note_view,
    change_note_view,
    register_request,
    create_category_view, change_status_view
)

urlpatterns = [
    path("", index, name="index"),
    path("register/", register_request, name="register"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("get_notes/", get_notes_view, name="get_notes"),
    path("get_categories/", get_categories_view, name="get_categories"),
    path("create_note/", create_note_view, name="create_note"),
    path('delete_note/<int:note_id>/', delete_note_view, name='delete_note'),
    path('change_note/<int:note_id>/', change_note_view, name='change_note'),
    path('create_category/', create_category_view, name='create_category'),
    path(
        'change_status/<int:note_id>/',
        change_status_view,
        name='change_status'
    ),

]
app_name = "notes_library"

notes_library/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from source import NOTE_STATUS_CHOICES, get_random_color


class Categories(models.Model):
    title = models.CharField(max_length=55)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Notes(models.Model):
    text = models.CharField(max_length=255)
    color = models.CharField(max_length=55, default='white')
    category = models.ForeignKey(
        Categories,
        on_delete=models.CASCADE,
        null=True
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=NOTE_STATUS_CHOICES)


class Colors(models.Model):
    color = models.CharField(max_length=55, default=get_random_color)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)


@receiver(post_save, sender=User)
def create_categories_for_new_user(sender, instance, created, **kwargs):
    if created:
        predefined_categories = [
            "Study",
            "Work",
            "Daily tasks",
            "Personal notes",
            "Shopping",
            "Events",
            "Travel",
            "Health",
            "Finances",
            "Hobby"
        ]
        for category_name in predefined_categories:
            category = Categories.objects.create(
                title=category_name,
                user=instance
            )
            color = get_random_color()
            Colors.objects.create(color=color, category=category)


post_save.connect(create_categories_for_new_user, sender=User)

notes_library/views.py
import json
import re

from datetime import datetime
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse

from notes_library.services import (
    get_user_by_id,
    get_notes,
    create_note,
    get_categories,
    get_id_by_category,
    get_color_by_category_id,
    delete_note_by_id,
    create_new_category,
    change_note_text,
    change_note_status
)
from source import count_unique_words


def index(request):
    user = request.user
    categories = get_categories(user_id=user.id)
    context = {
        'username': user.username,
        'categories': categories
    }
    return render(request, "notes_library/index.html", context=context)


def delete_note_view(request, note_id: int):
    user = get_user_by_id(request.user.id)
    deletion_successful = delete_note_by_id(note_id=note_id, user=user)
    if deletion_successful:
        return JsonResponse(
            {'message': 'Note deleted successfully'},
            status=200
        )
    else:
        return JsonResponse(
            {'error': 'Failed to delete note'},
            status=500
        )


def change_note_view(request, note_id):
    if request.method == 'PUT':
        try:
            data = json.loads(request.body)
            new_text = data.get('text', '')
            changed_note = change_note_text(text=new_text, note_id=note_id)
            return JsonResponse(changed_note)
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=400)
    return JsonResponse({'error': 'Method not allowed'}, status=405)


def create_note_view(request):
    if request.method == "POST":
        note_text = request.POST.get("note_text")
        user = request.user
        user_id = request.user.id
        if request.POST.get('category_name') != "Select a category":
            category = request.POST.get('category_name')
            category_id = get_id_by_category(
                category_name=category,
                user_id=user_id
            ).id
            color = get_color_by_category_id(
                category_id=category_id
            ).color
        else:
            color = "White"
            category_id = None

        create_note(
            user=user,
            text=note_text,
            color=color,
            category_id=category_id

        )
        return JsonResponse({"data": "sucess"})


def get_categories_view(request):
    formatted_notes = []
    user_id = request.user.id
    categories = get_categories(user_id=user_id)

    for category in categories:
        formatted_notes.append({'id': category.id, 'name': category.title})
    data = {"data": formatted_notes}
    return JsonResponse(data)


def get_notes_view(request):
    user_id = request.user.id
    notes = get_notes(user_id=user_id)
    category_id_filter = request.GET.get('category')
    date_filter = request.GET.get('date')
    word_count_filter = request.GET.get('word_count')
    unique_words_filter = request.GET.get('unique_words')
    status_filter = request.GET.get('status')

    if category_id_filter:
        notes = notes.filter(category_id=category_id_filter)

    if date_filter:
        date_obj = datetime.strptime(date_filter, '%Y-%m-%d')
        notes = notes.filter(created_at__date=date_obj)

    if word_count_filter:
        correct_notes = []
        word_count = int(word_count_filter)
        for note in notes:
            right_note = re.sub(r'[^\w\s]', '', note.text)
            note_length = len(right_note.split())
            if note_length >= word_count:
                correct_notes.append(note)
        notes = correct_notes

    if unique_words_filter:
        correct_notes = []
        unique_words = int(unique_words_filter)
        for note in notes:
            cleaned_note = re.sub(r'[^\w\s]', '', note.text)
            unique_word_count = count_unique_words(cleaned_note)

            if unique_word_count >= unique_words:
                correct_notes.append(note)
        notes = correct_notes
    if status_filter:
        correct_notes = []
        for note in notes:
            if note.status == status_filter:
                correct_notes.append(note)
        notes = correct_notes

    formatted_notes = [
        {
            "id": note.id,
            "text": note.text,
            "color": note.color,
            "status": note.status,
            "category": note.category.title
        }
        for note in notes
    ]

    data = {"data": formatted_notes}
    return JsonResponse(data)


def create_category_view(request):
    user = request.user
    if request.method == "POST":
        category_name = request.POST.get("category_text")
        creating_successful = create_new_category(
            category_name=category_name,
            user=user
        )
        if creating_successful:
            return JsonResponse(
                {'message': 'Category created successfully'},
                status=200
            )
        else:
            return JsonResponse(
                {'error': 'Failed to created category'},
                status=500
            )


def change_status_view(request, note_id: int):
    user_id = request.user.id
    if request.method == "POST":
        changing_successful = change_note_status(
            user_id=user_id,
            note_id=note_id
        )
        return JsonResponse(changing_successful)


def register_request(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        try:
            if form.is_valid():
                user = form.save()
                login(request, user)
                messages.success(request, "Registration successful.")

                return redirect(reverse("notes_library:index"))
            else:
                if "username" in form.errors:
                    messages.error(request, "Username is already taken.")
        except Exception as ex:
            print(ex)
    else:
        form = UserCreationForm()

    return render(
        request=request,
        template_name="registration/register.html",
        context={"register_form": form},
    )

templates/notes_library/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<div class="header">
  <p class="user-name">{{ user.username }}</p>
  <form action="{% url 'notes_library:logout' %}?next={% url 'notes_library:index' %}" method="post"
        class="navbar-brand">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Log Out</button>
  </form>
</div>
<div class="container">
  <div class="title">Notes Application</div>

  <div class="notes-section">
    <div class="section">
      <div class="filter-container">
        <h4>Filters:</h4>
        <label for="category-filter" class="filter-label">Category:</label>
        <select id="category-filter" class="form-control filter-select">
          <option value="">All Categories</option>
        </select>
        <label for="date-filter" class="filter-label">Date:</label>
        <input type="date" id="date-filter" class="form-control filter-input">
        <label for="word-count-filter" class="filter-label">Word Count:</label>
        <input type="number" id="word-count-filter" min="0" class="form-control filter-input">
        <label for="unique-words-filter" class="filter-label">Unique Words:</label>
        <input type="number" id="unique-words-filter" min="0" class="form-control filter-input">
        <label for="status-filter" class="filter-label">Status:</label>
        <select id="status-filter" class="form-control filter-select">
          <option value="">All</option>
          <option value="active">Active</option>
          <option value="archive">Archive</option>
        </select>
        <button id="apply-filters" class="apply-filters-btn">Apply Filters</button>
      </div>
      <div class="notes-container">

      </div>
      <div class="add-new-note">
        <button type="button" class="btn btn-main" id="create-note-button">＋ Create a new note</button>
      </div>

      <form id="create-note-form" style="display: none;">
        <textarea name="note_text" class="form-control" placeholder="Enter your note text"></textarea>

        <select id="category-select" name="category" class="form-control">
          <option value="">Select a category</option>
          <option value="Study">Study</option>
          <option value="Work">Work</option>
          <option value="Daily tasks">Daily tasks</option>
          <option value="Personal notes">Personal notes</option>
          <option value="Shopping">Shopping</option>
          <option value="Events">Events</option>
          <option value="Travel">Travel</option>
          <option value="Health">Health</option>
          <option value="Finances">Finances</option>
          <option value="Hobby">Hobby</option>
        </select>

        <input type="text" name="new_category" class="form-control" placeholder="Enter new category name"
               style="display: none;">
        <button type="submit" class="btn btn-primary">Create Note</button>
        <button type="button" class="btn btn-secondary" id="cancel-create-note">Cancel</button>
      </form>
      <div class="add-new-category">
        <button type="button" class="btn btn-main" id="create-new-category">＋ Create a new category</button>
      </div>
      <form id="create-category-form" style="display: none;">
        <textarea name="category_text" class="form-control" placeholder="Enter new category name"></textarea>

        <button type="submit" class="btn btn-primary">Create Category</button>
        <button type="button" class="btn btn-secondary" id="cancel-create-category">Cancel</button>
      </form>
    </div>
  </div>
</div>
{% else %}
<div class="header">
  <a href="{% url 'notes_library:register' %}" class="btn btn-primary">Register</a>
  <a href="{% url 'notes_library:login' %}" class="btn btn-success">Login</a>
</div>
<div class="container">
  <h1>Welcome to the Notes Application</h1>
  <p>To use our services, please <a href="{% url 'notes_library:register' %}">register</a> or <a
      href="{% url 'notes_library:login' %}">login</a>.</p>
</div>
{% endif %}
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}